const INPUT_MOVIE = 'INPUT_MOVIE'
const INPUTTING_MOVIE = 'INPUTTING_MOVIE'
const SEARCHING_MOVIE = 'SEARCHING_MOVIE'
const SEARCH_MOVIE = 'SEARCH_MOVIE'
const FIRST_REQUEST = 'FIRST_REQUEST'
const FIRST_REQUEST_SUCCESS = 'FIRST_REQUEST_SUCCESS'
const SECOND_REQUEST = 'SECOND_REQUEST'
const SECOND_REQUEST_SUCCESS = 'SECOND_REQUEST_SUCCESS'
const REQUEST_FAILED = 'REQUEST_FAILED'

export default {
    INPUT_MOVIE,
    INPUTTING_MOVIE,
    SEARCHING_MOVIE,
    SEARCH_MOVIE,
    FIRST_REQUEST,
    FIRST_REQUEST_SUCCESS,
    SECOND_REQUEST,
    SECOND_REQUEST_SUCCESS,
    REQUEST_FAILED
}